### ISSUE TITLE
Редизайн карточки проекта. 

### ISSUE THREAD

**Issue by fellz** [fellz/mesto.platform#1]
Нужно добавить картинку к проекту, чтобы было повеселее.
#design

**Comment by fellz** [comment]
Используем дизайн [отсюда](https://www.figma.com/file/hk324exNPyihGFinz74BQR/Mesto?node-id=0%3A1), добрые люди нарисовали экраны.  
Карточка 18.
![Screenshot_2](https://user-images.githubusercontent.com/96966/87870809-22997500-c9b4-11ea-8d62-00d40569ef20.jpg)

**Comment by kosgit** [comment]
### Поля
- Название
- Иконка
- Описание - короткая инфа о проекте, нужна для отображения в списках проектов чтобы привлечь внимание к дальнейшему изучению.
- Проблема. Лучше всего преподносить её в виде кейсов, во время чтения которых у людей возникают ассоциации и визуальные образы проблемы.
- Решение. Просто, кратко и доступно объясните решение проблемы, которое вы предлагаете.
- Прикрепленные картинки
- Аналитика: 
-- целевая аудитория
-- общий объем рынка
-- конкуренты
-- бизнес-модель продукта

Было бы хорошо, чтобы незаполненные поля не отображались в карточке проекта. Но были доступны на стадии редактирования и был счетчик кол-ва символов, дабы подсвечивать пользователям, что текста через чур много или мало.

**Comment by fellz** [comment]
Название есть, если речь о названии проекта. 
Отрасль, возможно. 
Описание проекта тоже есть. 
Проблема-решение, можно подумать.
Картинки уже встроены в систему, надо подумать, где их отображать в проекте. 
Аналитика это уже выходит за рамки MVP и нужно ли кому-то не понятно.

Насчет удобства редактирования текста ок, в идеале тут надо прикрутить редактор какой-нибудь не сложный.

**Comment by fellz** [comment]
Пока все выглядит так. 
![Screenshot_1](https://user-images.githubusercontent.com/96966/88594626-3014c600-d06a-11ea-9f82-fef66f10a50b.jpg)
Функционал по заявке пока в короткой версии проекта, где список всех проектов. Возможно есть смысл перенести в карточку проекта, а там оставить просто ссылку.
