### ISSUE TITLE
[Bug] Отображение кнопки "Оставить заявку" в списке проектов

### ISSUE THREAD

**Issue by kosgit** [fellz/mesto.platform#10]
![Скриншот 2020-07-29 17 16 14](https://user-images.githubusercontent.com/11017060/88811630-7a5b8b80-d1bf-11ea-92f9-db80086b60dc.png)
в списке проектов доступны кнопки с функционалом, который не доступен по переходу на страницу проекта:
1) Оставить заявку в "кто нужен"
2) Отставить заявку в "команды"

**Comment by fellz** [comment]
Там есть ряд ограничений. 
Сам себе ты заявку не отправляешь, если это твой проект и ты участвуешь в проекте, например. Второе ты должен быть залогинен в системе.
